server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 172.16.231.133:9300
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 172.16.231.140
    port: 5672
    virtual-host: /leyou
    username: leyou
    password: leyou

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
