server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 172.16.231.140
    virtual-host: /leyou
    username: leyou
    password: leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
leyou:
  sms:
    accessKeyId: LTAItNxDfk7MJMq # 你自己的accessKeyId
    accessKeySecret: HKUID121ZM7XoubErXjUFJq84dha8W # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_143714980 # 模板名称